### ISSUE TITLE
Navy Linux Member

### ISSUE THREAD

**Issue by domingoruiz** [jkonecny12/dotfiles#1]
Hello, I saw that you are a member of the Navy Linux project. I invite you to join the Slack channel of the project, so that you can keep up to date with all the work we do and so you can join a team and participate in the project. 

https://join.slack.com/t/nuevoespaciod-ghs4889/shared_invite/zt-kj37s3lu-~JkloN8UHgH38cyuD97V7Q

Thanks a lot.

**Comment by jkonecny12** [comment]
Hi, I think I've got the invitation from my post https://fosstodon.org/web/statuses/105496945035138225. However, I don't plan to use Navy Linux. I would like to use RHEL directly, Fedora or CentOS Stream. I joined the GH organization just to help you as a consultant, because I'm developer of the Anaconda installer.

However, I really don't want to have another chat solution. So, if you don't have mailing list, or you don't want to mail me directly when you have questions, then I should probably leave the organization because I won't be much of help to you.

**Comment by domingoruiz** [comment]
Hello and thanks for the interest shown. Indeed we need help with the Anaconda installer, in fact we are looking for someone to lead the installer team and you would be a very suitable person. Anyway, since you don't have time, thank you very much for the interest shown, and if we ever have a problem we will not hesitate to consult it with you. 

Thank you. 

A greeting.

**Comment by jkonecny12** [comment]
My thanks to you and I wish you good luck!
